name: Documentation issue Report
description: This report is related to the documentation 
title: "[Docs]: "
labels: ["docs", "support_request"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the necessary information to expedite the response.
  - type: input
    id: doc_link
    attributes:
      label: Documentation link 
      description: Please provide the link for the documentation issue
      placeholder: e.g. intel.com/content/www/us/en/developer/tools/openvino-toolkit/system-requirements.html
    validations:
      required: true
  - type: textarea
    id: build_description
    attributes:
      label: Build issue description
      description: What issue are you facing during the build/installation?
      placeholder: Please provide a detailed description of what happened
    validations:
      required: true
      label: Issue submission checklist
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/intel/intel-one-mono/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I report the documentation issue. It's not a question
          required: true
